relationship_stereotype:
  name: structuration
  directed: true
  source_end:
    allowed:
    - Quality
    min: 0
    max: "*"
    readOnly: undefined
  target_end:
    allowed:
    - Quality
    - Mode
    min: 1
    max: 1
    readOnly: undefined
  binary_properties:
    reflexivity: false
    transitivity: false
    symmetry: false
    cyclicity: undefined
