class_stereotype:
  name: Quality
  parent: Aspect
  provides_identity: true
  identity_principle: single
  rigidity: rigid
  dependency: mandatory
  supertypes:
  - Category
  - Mixin
  subtypes:
  - Subkind
  - Role
  - Phase
  forbidden_associations:
  - ComponentOf
  - SubCollectionOf
  - MemberOf
  - SubQuantityOf
  - Derivation
  abstract: true
