class_stereotype:
  name: RoleMixin
  parent: AntiRigidNonSortal
  provides_identity: false
  identity_principle: multiple
  rigidity: antirigid
  dependency: mandatory
  supertypes:
  - Mixin
  - RoleMixin
  - Category
  - PhaseMixin
  subtypes:
  - Role
  - RoleMixin
  forbidden_associations:
  - Structuration
  abstract: true
