aggregation_stereotype:
  name: subQuantityOf
  directed: true
  source_end:
    allowed:
    - Quantity
    min: 1
    max: 1
    readOnly: undefined
  target_end:
    allowed:
    - Quantity
    min: 1
    max: 1
    readOnly: undefined
  binary_properties:
    reflexivity: false
    transitivity: true
    symmetry: false
    cyclicity: false
