aggregation_stereotype:
  name: containment
  directed: true
  source_end:
    allowed: *
    min: 1
    max: 1
    readOnly: undefined
  target_end:
    allowed: Quantity
    min: 1
    max: 1
    readOnly: undefined
  binary_properties:
    reflexivity: false
    transitivity: false
    symmetry: false
    cyclicity: false
