class_stereotype:
  name: Mixin
  parent: SemiRigidNonSortal
  provides_identity: false
  identity_principle: multiple
  rigidity: semirigid
  dependency: optional
  supertypes:
  - Mixin
  - Category
  subtypes:
	- Category
	- Collective
	- Kind
	- Mixin
	- Mode
	- Phase
	- Phase
	- PhaseMixin
	- Quality
	- Quantity
	- Relator
	- Role
	- Role
	- RoleMixin
	- Subkind
  forbidden_associations:
  - Structuration
  abstract: true
