class_stereotype:
  name: Mixin
  parent: SemiRigidNonSortal
  provides_identity: false
  identity_principle: multiple
  rigidity: semirigid
  dependency: optional
  supertypes:
  - Mixin
  subtypes:
  - Subkind
  - Kind
  - Collective
  - Quantity
  - Category
  - Mixin
  - Role
  - Phase
  - RoleMixin
  - PhaseMixin
  - Relator
  - Quality
  - Mode
  abstract: true
