class_stereotype:
  name: Category
  parent: RigidNonSortal
  provides_identity: false
  identity_principle: multiple
  rigidity: rigid
  dependency: optional
  supertypes:
  - Category
  - Mixin
  subtypes:
  - Category
  - Collective
  - Kind
  - Mixin
  - Mode
  - Phase
  - Phase
  - PhaseMixin
  - Quality
  - Quantity
  - Relator
  - Role
  - Role
  - RoleMixin
  - Subkind
  forbidden_associations:
  - Structuration
  abstract: true
