class_stereotype:
  name: Category
  parent: Endurant
  provides_identity: false
  identity_principle: multiple
  rigidity: rigid
  dependency: optional
  supertypes:
  - Category
  - Mixin
  subtypes:
  - Kind
  - Subkind
  - Collective
  - Quantity
  - Relator
  - Category
  - Mode
  - Quality
  - Role
  - Phase
  - RoleMixin
  - PhaseMixin
  - Mixin
  forbidden_associations:
  - Structuration
  abstract: true
