class_stereotype:
  name: Phase
  parent: Endurant
  provides_identity: false
  identity_principle: simple
  rigidity: antirigid
  dependency: optional
  supertypes:
  - Kind
  - Subkind
  - Collective
  - Quantity
  - Relator
  - Phase
  - Mixin
  - PhaseMixin
  - Mode
  - Quality
  - Category
  subtypes:
  - Phase
  - Role
  forbidden_associations:
  - Structuration
  abstract: undefined
