class_stereotype:
  name: Role
  parent: AntiRigidSortal
  provides_identity: false
  identity_principle: simple
  rigidity: antirigid
  dependency: mandatory
  supertypes:
  - Kind
  - Subkind
  - Collective
  - Phase
  - Quantity
  - Relator
  - Role
  - RoleMixin
  - Mixin
  - Mode
  - Quality
  - Category
  - PhaseMixin
  subtypes:
  - Role
  forbidden_associations:
  - Structuration
  abstract: undefined
