class_stereotype:
  name: PhaseMixin
  parent: AntiRigidNonSortal
  provides_identity: false
  identity_principle: multiple
  rigidity: antirigid
  dependency: mandatory
  supertypes:
  - Mixin
  - PhaseMixin
  subtypes:
  - Phase
  - PhaseMixin
  abstract: true
