class_stereotype:
  name: PhaseMixin
  parent: Endurant
  provides_identity: false
  identity_principle: multiple
  rigidity: antirigid
  dependency: mandatory
  supertypes:
  - Mixin
  - PhaseMixin
  - Category
  subtypes:
  - Phase
  - PhaseMixin
  - Role
  - RoleMixin
  forbidden_associations:
  - Structuration
  abstract: true
