class_stereotype:
  name: PhaseMixin
  parent: AntiRigidNonSortal
  provides_identity: false
  identity_principle: multiple
  rigidity: antirigid
  dependency: mandatory
  supertypes:
	- Category
	- Mixin
	- PhaseMixin
	- RoleMixin
  subtypes:
	- Phase
	- PhaseMixin
	- Role
	- RoleMixin
  forbidden_associations:
  - Structuration
  abstract: true
