relationship_stereotype:
  name: derivation
  directed: true
  source_end:
    allowed:
    - Relator
    min: 1
    max: 1
    readOnly: undefined
  target_end:
    allowed:
    - material
    min: 1
    max: 1
    readOnly: undefined
  binary_properties:
    reflexivity: false
    transitivity: false
    symmetry: false
    cyclicity: false
